import { spawn } from 'node:child_process'
import { existsSync, writeFileSync } from 'node:fs'
import { get as httpGet } from 'node:http'
import { createServer } from 'node:net'
import path from 'node:path'

export type LoginResult = { ok: true } | { ok: false; error: 'no-browser' | 'cdp-timeout' | 'no-cookies' | 'failed' }

interface WsLike {
  send(data: string): void
  close(): void
  addEventListener(type: 'open' | 'error', listener: () => void): void
  addEventListener(type: 'message', listener: (event: { data?: unknown }) => void): void
}

interface CdpCookie {
  name: string
  value: string
  domain: string
  path: string
  expires: number
  httpOnly: boolean
  secure: boolean
  session: boolean
}

// Login pages opened as tabs. CDP Storage.getCookies captures cookies for every
// domain in the profile, so the user can sign in to whichever platforms they need
// in one session and a single cookies.txt covers them all.
const LOGIN_URLS = [
  'https://www.youtube.com/',
  'https://www.tiktok.com/login',
  'https://www.facebook.com/login/',
  'https://www.instagram.com/accounts/login/',
]

function findBrowser(): string | null {
  const candidates = [
    path.join(process.env['ProgramFiles'] ?? '', 'Google/Chrome/Application/chrome.exe'),
    path.join(process.env['ProgramFiles(x86)'] ?? '', 'Google/Chrome/Application/chrome.exe'),
    path.join(process.env['LOCALAPPDATA'] ?? '', 'Google/Chrome/Application/chrome.exe'),
    path.join(process.env['ProgramFiles(x86)'] ?? '', 'Microsoft/Edge/Application/msedge.exe'),
    path.join(process.env['ProgramFiles'] ?? '', 'Microsoft/Edge/Application/msedge.exe'),
  ]

  return candidates.find((candidate) => candidate && existsSync(candidate)) ?? null
}

function getFreePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const server = createServer()
    server.listen(0, '127.0.0.1', () => {
      const address = server.address()
      if (address && typeof address === 'object') {
        const { port } = address
        server.close(() => resolve(port))
      } else {
        server.close(() => reject(new Error('no-port')))
      }
    })
    server.on('error', reject)
  })
}

function httpJson(url: string): Promise<unknown> {
  return new Promise((resolve, reject) => {
    const req = httpGet(url, (res) => {
      let body = ''
      res.setEncoding('utf8')
      res.on('data', (chunk) => {
        body += chunk
      })
      res.on('end', () => {
        try {
          resolve(JSON.parse(body))
        } catch (error) {
          reject(error)
        }
      })
    })
    req.on('error', reject)
    req.setTimeout(2000, () => req.destroy(new Error('timeout')))
  })
}

async function waitForDebuggerUrl(port: number, timeoutMs: number): Promise<string | null> {
  const deadline = Date.now() + timeoutMs
  while (Date.now() < deadline) {
    try {
      const info = (await httpJson(`http://127.0.0.1:${port}/json/version`)) as {
        webSocketDebuggerUrl?: string
      }
      if (info.webSocketDebuggerUrl) {
        return info.webSocketDebuggerUrl
      }
    } catch {
      // endpoint not ready yet
    }
    await new Promise((resolve) => setTimeout(resolve, 500))
  }
  return null
}

function toNetscape(cookies: CdpCookie[]): string {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by FLASH MEDIA']
  for (const cookie of cookies) {
    const domain = cookie.domain || ''
    const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE'
    const secure = cookie.secure ? 'TRUE' : 'FALSE'
    const expiry = cookie.session || !cookie.expires || cookie.expires < 0 ? 0 : Math.floor(cookie.expires)
    lines.push(
      [domain, includeSubdomains, cookie.path || '/', secure, String(expiry), cookie.name, cookie.value].join('\t'),
    )
  }
  return `${lines.join('\n')}\n`
}

// Launch a real Chrome/Edge window with a dedicated profile + remote debugging,
// let the user log in, then capture decrypted cookies via the DevTools Protocol
// (bypasses Google's embedded-browser block and Chrome's App-Bound Encryption).
export async function loginAndCaptureCookies(
  profileDir: string,
  cookiesFilePath: string,
): Promise<LoginResult> {
  const browserExe = findBrowser()
  if (!browserExe) {
    return { ok: false, error: 'no-browser' }
  }

  let port: number
  try {
    port = await getFreePort()
  } catch {
    return { ok: false, error: 'failed' }
  }

  const child = spawn(
    browserExe,
    [
      `--user-data-dir=${profileDir}`,
      `--remote-debugging-port=${port}`,
      '--remote-allow-origins=*',
      '--no-first-run',
      '--no-default-browser-check',
      ...LOGIN_URLS,
    ],
    { windowsHide: false },
  )

  const wsUrl = await waitForDebuggerUrl(port, 20000)
  if (!wsUrl) {
    try {
      child.kill()
    } catch {
      // ignore
    }
    return { ok: false, error: 'cdp-timeout' }
  }

  let latest: CdpCookie[] = []

  // WebSocket is a Node 22 global; type it loosely to avoid needing the DOM lib.
  const WebSocketCtor = (globalThis as { WebSocket?: new (url: string) => WsLike }).WebSocket
  if (!WebSocketCtor) {
    try {
      child.kill()
    } catch {
      // ignore
    }
    return { ok: false, error: 'failed' }
  }

  await new Promise<void>((resolve) => {
    let ws: WsLike | null = null
    let messageId = 0
    let pollTimer: ReturnType<typeof setInterval> | null = null

    const cleanup = () => {
      if (pollTimer) {
        clearInterval(pollTimer)
        pollTimer = null
      }
      try {
        ws?.close()
      } catch {
        // ignore
      }
    }

    try {
      ws = new WebSocketCtor(wsUrl)
    } catch {
      resolve()
      return
    }

    ws.addEventListener('open', () => {
      const requestCookies = () => {
        messageId += 1
        ws?.send(JSON.stringify({ id: messageId, method: 'Storage.getCookies', params: {} }))
      }
      requestCookies()
      pollTimer = setInterval(requestCookies, 1500)
    })

    ws.addEventListener('message', (event: { data?: unknown }) => {
      try {
        const data = typeof event.data === 'string' ? event.data : ''
        const parsed = JSON.parse(data) as { result?: { cookies?: CdpCookie[] } }
        const cookies = parsed.result?.cookies
        if (cookies && cookies.length > 0) {
          latest = cookies
        }
      } catch {
        // ignore non-JSON / unrelated frames
      }
    })

    ws.addEventListener('error', () => {
      // keep waiting for the browser to close
    })

    // Done when the user closes the browser window.
    child.on('exit', () => {
      cleanup()
      resolve()
    })
  })

  if (latest.length === 0) {
    return { ok: false, error: 'no-cookies' }
  }

  try {
    writeFileSync(cookiesFilePath, toNetscape(latest), 'utf8')
  } catch {
    return { ok: false, error: 'failed' }
  }

  return { ok: true }
}
